CI: add step to run tests
Had to update .netCore2.x to .NET6 in the project
file for this to successfully run without error:

```
tarting test execution, please wait...
A total of 1 test files matched the specified pattern.
Testhost process exited with error: You must install or update .NET to run this application.
App: /github/home/.nuget/packages/microsoft.testplatform.testhost/15.8.0/lib/netstandard1.5/testhost.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '2.0.0' (x64)
.NET location: /usr/lib/dotnet/
The following frameworks were found:
  6.0.26 at [/usr/lib/dotnet/shared/Microsoft.NETCore.App]
Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed
To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.0.0&arch=x64&rid=ubuntu.22.04-x64
. Please check the diagnostic logs for more information.

Test Run Aborted.
Error: Process completed with exit code 1.
```