FX.Tests: add FSharp.Core ref to fix build
To try to fix this build error:

```
/__w/FX/FX/src/FX.Tests/LimitOrders.cs(5,17): error CS0234: The type or namespace name 'FSharp' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
[/__w/FX/FX/src/FX.Tests/FX.Tests.csproj]
/__w/FX/FX/src/FX.Tests/LimitOrders.cs(16,25): error CS0246: The type or namespace name 'FSharpOption<>' could not be found (are you missing a using directive or an assembly reference?)
[/__w/FX/FX/src/FX.Tests/FX.Tests.csproj]
    7 Warning(s)
    2 Error(s)
```